#!/usr/bin/python3

"""
Lê, na entrada padrão, um programa na linguagem de montagem da máquina
virtual e retorna um programa em C que executa este programa.

Uso:
    montador < entrada > saida
"""
from sys import stdin

l = stdin.readline()
ip = 0

tabsim = {}

print("#include <stdio.h>")
print('#include "maq.h"\n')
print("INSTR programa[] = {")
while l:
    label = op = ""
    arg   = 0
    try:
        l = l[:l.index('#')]                     #jogando fora os comentários
    except:
        pass
    keys = l.split()
    if len(keys) > 0 and keys[0].endswith(":"):  #caso em que tem labels
        label = keys[0][:-1]                     #jogando fora o ':'
        tabsim[label]=ip                         #guardando o endereço da label
        keys.pop(0)
    if len(keys) > 0:               #definindo o opcode da instrução
        op = keys.pop(0)
    if len(keys) > 0:               #definindo o argumento da instrução
        arg = keys.pop(0)
        if arg in tabsim:           #se houver label no argumento
            arg = tabsim[arg]       #argumento recebe o endereço da label
    if op != "":
        print("  {%s, %s},"%(op,arg))   #deixa em formato de vetor
    else:
        print()                     #se houver uma linha em branco,
        ip-=1                       #decrementar o ip
    l = stdin.readline()
    ip += 1
print("};\n")

print("int main(int argc, char *argv) {")
print("\tMaquina *maq = cria_maquina(programa);")
print("\texec_maquina(maq, 100);")
print("\tdestroi_maquina(maq);")
print("\treturn 0;")
print("}")
    




# Local variables:
# mode: python
# End:

